services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:15.2.1
    restart: unless-stopped
    environment:
      WG_HOST: "[YOUR_PUBLIC_IP]"
      PASSWORD_HASH: "$2b$12$coPqCsPtcFO.Ab99xylBNOW4.Iu7OOA2/ZIboHN6/oyxca3MWo7fW"
      WG_DEFAULT_DNS: "1.1.1.1"
      WG_ALLOWED_IPS: 0.0.0.0/0, ::/0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ${APP_DATA_DIR}/data:/etc/wireguard
    ports:
      - ${APP_PORT}:51820/udp
      - 51821:51821/tcp
    labels:
      runtipi.managed: "true"
    networks:
      - tipi_main_network
networks:
  tipi_main_network:
    external: true
